on:
  push:
  pull_request:

name: build_docker

jobs:
  build_docker:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Build the Docker image
        run: ./build_docker_image.sh

      - name: View the Docker images
        run: sudo docker image ls

#      - name: Build the Docker container
#        run: ./build_docker_container.sh
#
#      - name: View the Docker container
#        run: ls

