# Build the Singularity container
# and run it minimally

on:
  push:
  pull_request:

name: build_singularity

jobs:
  build_singularity:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        singularity_version:
          - '3.7.4'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Clean up space, from https://github.com/actions/virtual-environments/issues/709#issuecomment-612569242
        run: |
          sudo rm -rf "/usr/local/share/boost" \
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: How much disk space we have? We need 6 GB
        run: df -h

      - name: Build the Singularity container
        run: ./build_singularity_container.sh

      - name: Run the Singularity container
        run: singularity run gcae.sif --help

